# Generated by Django 5.2.3 on 2025-06-22 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1_media_manger', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_created', models.DateTimeField(auto_now_add=True)),
                ('cast_updated', models.DateTimeField(auto_now=True)),
                ('castmedia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app3_cast', to='app1_media_manger.castmedia')),
            ],
        ),
        migrations.CreateModel(
            name='CastCoreDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=20)),
                ('born_date', models.DateField()),
                ('death_date', models.DateField(blank=True, null=True)),
                ('otherwork', models.TextField(blank=True)),
                ('cast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='core_detail', to='app3_cast.cast')),
                ('children', models.ManyToManyField(blank=True, related_name='child_of', to='app3_cast.cast')),
                ('relatives', models.ManyToManyField(blank=True, related_name='relative_of', to='app3_cast.cast')),
                ('spouses', models.ManyToManyField(blank=True, related_name='spouse_of', to='app3_cast.cast')),
            ],
        ),
        migrations.CreateModel(
            name='CastKnownFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_for', to='app3_cast.cast')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['moviemedia', 'tvshowmedia']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
