# Generated by Django 5.2.3 on 2025-07-15 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1_media_manger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_created', models.DateTimeField(auto_now_add=True)),
                ('cast_updated', models.DateTimeField(auto_now=True)),
                ('castmedia', models.OneToOneField(help_text='write name of CastMedia', on_delete=django.db.models.deletion.CASCADE, related_name='app3_cast', to='app1_media_manger.castmedia')),
            ],
        ),
        migrations.CreateModel(
            name='CastCoreDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=20)),
                ('born_date', models.DateField()),
                ('death_date', models.DateField(blank=True, null=True)),
                ('spouses', models.JSONField(blank=True, default=list)),
                ('children', models.JSONField(blank=True, default=list)),
                ('relatives', models.JSONField(blank=True, default=list)),
                ('otherwork', models.JSONField(blank=True, default=list)),
                ('cast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='core_detail', to='app3_cast.cast')),
            ],
        ),
    ]
