# Generated by Django 5.2.3 on 2025-06-23 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_media_manger', '0003_tvshowmedia_slug'),
        ('app3_cast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castcoredetail',
            name='cast',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='core_detail', to='app1_media_manger.castmedia'),
        ),
        migrations.AlterField(
            model_name='castknownfor',
            name='cast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_for', to='app1_media_manger.castmedia'),
        ),
    ]
