# Generated by Django 5.2.3 on 2025-06-23 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_cast', '0002_alter_castcoredetail_cast_alter_castknownfor_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castcoredetail',
            name='cast',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='core_detail', to='app3_cast.cast'),
        ),
        migrations.AlterField(
            model_name='castknownfor',
            name='cast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_for', to='app3_cast.cast'),
        ),
    ]
