# Generated by Django 5.2.3 on 2025-06-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_cast', '0003_alter_castcoredetail_cast_alter_castknownfor_cast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castcoredetail',
            name='children',
        ),
        migrations.RemoveField(
            model_name='castcoredetail',
            name='relatives',
        ),
        migrations.RemoveField(
            model_name='castcoredetail',
            name='spouses',
        ),
        migrations.AddField(
            model_name='castcoredetail',
            name='children',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='castcoredetail',
            name='relatives',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='castcoredetail',
            name='spouses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
