# Generated by Django 5.2.3 on 2025-06-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_cast', '0004_remove_castcoredetail_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castcoredetail',
            name='otherwork',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
