# Generated by Django 5.2.3 on 2025-06-23 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_media_manger', '0003_tvshowmedia_slug'),
        ('app3_cast', '0005_alter_castcoredetail_otherwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='castmedia',
            field=models.OneToOneField(help_text='write name of CastMedia', on_delete=django.db.models.deletion.CASCADE, related_name='app3_cast', to='app1_media_manger.castmedia'),
        ),
    ]
