# Generated by Django 5.2.3 on 2025-06-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3_cast', '0006_alter_cast_castmedia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CastKnownFor',
        ),
    ]
