# Generated by Django 5.2.3 on 2025-07-06 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1_media_manger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_created', models.DateTimeField(auto_now_add=True)),
                ('creator_updated', models.DateTimeField(auto_now=True)),
                ('creatormedia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app4_creator', to='app1_media_manger.creatormedia')),
            ],
        ),
        migrations.CreateModel(
            name='CreatorCoreDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=20)),
                ('born_date', models.DateField()),
                ('death_date', models.DateField(blank=True, null=True)),
                ('spouses', models.JSONField(blank=True, default=list)),
                ('children', models.JSONField(blank=True, default=list)),
                ('relatives', models.JSONField(blank=True, default=list)),
                ('otherwork', models.JSONField(blank=True, default=list)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_core_detail', to='app4_creator.creator')),
            ],
        ),
    ]
