# Generated by Django 5.2.3 on 2025-06-23 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1_media_manger', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_created', models.DateTimeField(auto_now_add=True)),
                ('creator_updated', models.DateTimeField(auto_now=True)),
                ('creatormedia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app4_creator', to='app1_media_manger.creatormedia')),
            ],
        ),
        migrations.CreateModel(
            name='CreatorCoreDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=20)),
                ('born_date', models.DateField()),
                ('death_date', models.DateField(blank=True, null=True)),
                ('otherwork', models.TextField(blank=True)),
                ('children', models.ManyToManyField(blank=True, related_name='child_of', to='app4_creator.creator')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_core_detail', to='app4_creator.creator')),
                ('relatives', models.ManyToManyField(blank=True, related_name='relative_of', to='app4_creator.creator')),
                ('spouses', models.ManyToManyField(blank=True, related_name='spouse_of', to='app4_creator.creator')),
            ],
        ),
        migrations.CreateModel(
            name='CreatorKnownFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['moviemedia', 'tvshowmedia']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_known_for', to='app4_creator.creator')),
            ],
        ),
    ]
