# Generated by Django 5.2.3 on 2025-06-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4_creator', '0002_delete_creatorknownfor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorcoredetail',
            name='children',
        ),
        migrations.AlterField(
            model_name='creatorcoredetail',
            name='otherwork',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RemoveField(
            model_name='creatorcoredetail',
            name='relatives',
        ),
        migrations.RemoveField(
            model_name='creatorcoredetail',
            name='spouses',
        ),
        migrations.AddField(
            model_name='creatorcoredetail',
            name='children',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='creatorcoredetail',
            name='relatives',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='creatorcoredetail',
            name='spouses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
