# Generated by Django 5.2.3 on 2025-06-22 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1_media_manger', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_created', models.DateTimeField(auto_now_add=True)),
                ('writer_updated', models.DateTimeField(auto_now=True)),
                ('writermedia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app5_writer', to='app1_media_manger.writermedia')),
            ],
        ),
        migrations.CreateModel(
            name='WriterCoreDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=20)),
                ('born_date', models.DateField()),
                ('death_date', models.DateField(blank=True, null=True)),
                ('otherwork', models.TextField(blank=True)),
                ('children', models.ManyToManyField(blank=True, related_name='child_of', to='app5_writer.writer')),
                ('relatives', models.ManyToManyField(blank=True, related_name='relative_of', to='app5_writer.writer')),
                ('spouses', models.ManyToManyField(blank=True, related_name='spouse_of', to='app5_writer.writer')),
                ('writer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='writer_core_detail', to='app5_writer.writer')),
            ],
        ),
        migrations.CreateModel(
            name='WriterKnownFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['moviemedia', 'tvshowmedia']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_known_for', to='app5_writer.writer')),
            ],
        ),
    ]
