# Generated by Django 5.2.3 on 2025-06-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5_writer', '0002_delete_writerknownfor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writercoredetail',
            name='children',
        ),
        migrations.AlterField(
            model_name='writercoredetail',
            name='otherwork',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RemoveField(
            model_name='writercoredetail',
            name='relatives',
        ),
        migrations.RemoveField(
            model_name='writercoredetail',
            name='spouses',
        ),
        migrations.AddField(
            model_name='writercoredetail',
            name='children',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='writercoredetail',
            name='relatives',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='writercoredetail',
            name='spouses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
