# Generated by Django 5.2.3 on 2025-06-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6_movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movietechspecs',
            name='color',
            field=models.CharField(choices=[('color', 'Color'), ('bw', 'Black and White')], default='color', max_length=20),
        ),
        migrations.AlterField(
            model_name='movietechspecs',
            name='sound_mix',
            field=models.CharField(choices=[('mono', 'Mono'), ('stereo', 'Stereo'), ('dolby_digital', 'Dolby Digital'), ('dts', 'DTS'), ('dolby_atmos', 'Dolby Atmos'), ('sdds', 'SDDS'), ('auro_3d', 'Auro 3D'), ('imax_6_track', 'IMAX 6-Track')], default='dolby_atmos', max_length=30),
        ),
    ]
