# Generated by Django 5.2.3 on 2025-06-25 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app6_movie', '0002_alter_movietechspecs_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieratingreview',
            old_name='description',
            new_name='review',
        ),
    ]
