# Generated by Django 5.2.3 on 2025-06-25 13:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app6_movie', '0003_rename_description_movieratingreview_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermovieviewed',
            old_name='user',
            new_name='user_viewed',
        ),
        migrations.RenameField(
            model_name='usermoviewatchlist',
            old_name='user',
            new_name='user_watchlist',
        ),
        migrations.AlterUniqueTogether(
            name='usermovieviewed',
            unique_together={('user_viewed', 'movie')},
        ),
        migrations.AlterUniqueTogether(
            name='usermoviewatchlist',
            unique_together={('user_watchlist', 'movie')},
        ),
    ]
