# Generated by Django 5.2.3 on 2025-06-25 13:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app6_movie', '0004_rename_user_usermovieviewed_user_viewed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='movievotes',
            old_name='user',
            new_name='user_vote',
        ),
        migrations.AlterUniqueTogether(
            name='movievotes',
            unique_together={('user_vote', 'movie')},
        ),
    ]
