# Generated by Django 5.2.3 on 2025-06-26 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6_movie', '0005_rename_user_movievotes_user_vote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoviewatchlist',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_watchlisted_by', to='app6_movie.movie'),
        ),
    ]
