# Generated by Django 5.2.3 on 2025-06-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_media_manger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonmedia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seasonmedia',
            name='season_number',
            field=models.PositiveIntegerField(),
        ),
    ]
