# Generated by Django 5.2.3 on 2025-06-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_media_manger', '0002_seasonmedia_id_alter_seasonmedia_season_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshowmedia',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
