# Generated by Django 5.2.3 on 2025-06-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_media_manger', '0003_tvshowmedia_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodemedia',
            name='episode_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
