# Generated by Django 5.2.3 on 2025-06-28 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_media_manger', '0004_episodemedia_episode_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshowmedia',
            old_name='slug',
            new_name='tvshow_slug',
        ),
    ]
