# Generated by Django 5.2.3 on 2025-06-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_media_manger', '0005_rename_slug_tvshowmedia_tvshow_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemedia',
            name='movie_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
