# Generated by Django 5.2.3 on 2025-06-27 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app10_episode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='episodemedia',
        ),
        migrations.DeleteModel(
            name='EpisodeGeneralDetail',
        ),
        migrations.DeleteModel(
            name='EpisodeRatingReview',
        ),
        migrations.DeleteModel(
            name='EpisodeViewed',
        ),
        migrations.DeleteModel(
            name='EpisodeVotes',
        ),
        migrations.DeleteModel(
            name='EpisodeWatchlist',
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
    ]
