# Generated by Django 5.2.3 on 2025-06-27 03:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app10_episode', '0002_remove_episode_episodemedia_and_more'),
        ('app1_media_manger', '0003_tvshowmedia_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_created', models.DateTimeField(auto_now_add=True)),
                ('episode_updated', models.DateTimeField(auto_now=True)),
                ('episodemedia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app10_episode', to='app1_media_manger.episodemedia')),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeGeneralDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('is_original', models.BooleanField()),
                ('avg_rating', models.FloatField(default=0)),
                ('number_rating', models.IntegerField(default=0)),
                ('storyline', models.TextField()),
                ('episode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='episode_general_detail', to='app10_episode.episode')),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeRatingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('review', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_reviews', to='app10_episode.episode')),
                ('user_tvshow_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_episode_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_viewed_by', to='app10_episode.episode')),
                ('user_viewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'unique_together': {('user_viewed', 'episode')},
            },
        ),
        migrations.CreateModel(
            name='EpisodeVotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('love', 'Love'), ('appreciate', 'Appreciate'), ('insightful', 'Insightful'), ('funny', 'Funny'), ('excited', 'Excited')], max_length=20)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_votes', to='app10_episode.episode')),
                ('user_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_vote', 'episode')},
            },
        ),
        migrations.CreateModel(
            name='EpisodeWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_watchlisted_by', to='app10_episode.episode')),
                ('user_watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user_watchlist', 'episode')},
            },
        ),
    ]
