# Generated by Django 5.2.3 on 2025-06-28 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app10_episode', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episoderatingreview',
            old_name='user_tvshow_review',
            new_name='user_episode_review',
        ),
    ]
