# Generated by Django 5.2.3 on 2025-06-29 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app10_episode', '0004_rename_user_tvshow_review_episoderatingreview_user_episode_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodeviewed',
            name='user_viewed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_viewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='episodewatchlist',
            name='user_watchlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
